"""Report writer -- local markdown & JSON report generation."""

import json
import os
import re
import time
from datetime import datetime, timezone
from pathlib import Path
from collections import defaultdict

from monitor.config import MIRROR_DIR, REPORT_DIR, DIFF_DIR
from monitor.logger import log


def write_monitor_report(category: str, data: dict):
    _ensure_dirs()
    ts = datetime.now(timezone.utc)
    filename = f"{ts.strftime('%Y%m%d_%H%M%S')}_{category}.json"
    path = REPORT_DIR / filename
    report = {
        "timestamp": ts.strftime("%Y-%m-%d %H:%M:%S UTC"),
        "category": category,
        "data": data,
    }
    path.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    log(f"Report written: {path.name}", "FILE")

    latest = REPORT_DIR / f"latest_{category}.json"
    latest.write_text(path.name, encoding="utf-8")


def write_changelog(changes: list):
    from monitor.noise_filter import diff_has_real_changes

    changelog_path = DIFF_DIR / "CHANGELOG.md"
    DIFF_DIR.mkdir(parents=True, exist_ok=True)

    existing = _parse_changelog(changelog_path)
    new_entries = {}

    for url, path, diff_content, rel in changes:
        sz = _fmt_size(path.stat().st_size)
        is_real = diff_content and diff_has_real_changes(diff_content)

        if not is_real and diff_content is None:
            continue

        old_entry = existing.get(url, {})
        history = []
        if old_entry:
            for h in old_entry.get("history", []):
                history.append(h)

        current_lines = diff_content.splitlines() if diff_content else None
        new_entries[url] = {
            "rel": rel,
            "size": sz,
            "current_diff": current_lines,
            "history": history,
        }

    if not new_entries:
        return

    lines = [
        "# Change Report",
        "",
        f"Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
        "",
        f"**{len(new_entries)} file(s) with meaningful changes**",
        "",
    ]

    for url in sorted(new_entries.keys()):
        entry = new_entries[url]
        lines += [f"### {url}", f"`{entry['rel']}` ({entry['size']})", ""]

        if entry["current_diff"] is not None:
            lines.append("```diff")
            lines += _filter_noise_diff_lines(entry["current_diff"])
            if lines[-1] == "```":
                lines[-1] = ""
            lines.append("```")
            lines.append("")
        else:
            lines.append("*No line-level diff available*")
            lines.append("")

        for h in entry["history"]:
            ts = h.get("timestamp", "")
            label = f"Previous diff ({ts})" if ts else "Previous diff"
            hist_lines = _filter_noise_diff_lines(h.get("lines", []))
            lines.append("<details>")
            lines.append(f"<summary>{label}</summary>")
            lines.append("")
            lines.append("```diff")
            if hist_lines and hist_lines[-1] == "```":
                lines += hist_lines[:-1]
            else:
                lines += hist_lines
            lines.append("```")
            lines.append("")
            lines.append("</details>")
            lines.append("")

    lines.append("*Auto-generated by monitor*")
    lines.append("")

    changelog_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    log(f"Changelog written: {changelog_path} ({len(new_entries)} files)", "FILE")


def clean_old_reports(max_age_hours: int = 72):
    cutoff = time.time() - (max_age_hours * 3600)
    for f in REPORT_DIR.glob("*.json"):
        if f.name.startswith("latest_"):
            continue
        try:
            if f.stat().st_mtime < cutoff:
                f.unlink()
        except OSError:
            pass


def generate_manifest_report(stats_by_dir: dict, total_files: int, total_size: int):
    lines = [
        "# project-skyscraper.com -- Complete Mirror Manifest",
        "",
        f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
        f"**Source:** https://project-skyscraper.com",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| **Total files** | {total_files} |",
        f"| **Total size** | {_fmt_size(total_size)} |",
        "",
        "## Section Breakdown",
        "",
        "| Section | Files | Size |",
        "|---------|-------|------|",
    ]
    for section in sorted(stats_by_dir):
        if section in (".git", "__pycache__", "state", "monitor_reports"):
            continue
        d = stats_by_dir[section]
        lines.append(f"| **{section}/** | {d['files']} | {_fmt_size(d['size'])} |")
    lines += ["", "*Auto-generated by monitor*", ""]
    manifest_path = MIRROR_DIR / "MIRROR_MANIFEST.md"
    manifest_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    log(f"Manifest written: {manifest_path}", "FILE")


def generate_unpublished_report(unpublished_posts: list, unpublished_pages: list):
    if not unpublished_posts and not unpublished_pages:
        return

    total = len(unpublished_posts) + len(unpublished_pages)
    lines = [
        "# Unpublished / Restricted IDs Report",
        "",
        f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
        f"**Source:** https://project-skyscraper.com/wp-json/wp/v2/{{posts,pages}}/{{id}}",
        "",
        "IDs returning 401 or 403 indicate content that exists but is not publicly",
        "accessible (drafts, private, etc.).",
        "",
        "## Summary",
        "",
        "| Type | Count |",
        "|------|-------|",
        f"| **Posts** | {len(unpublished_posts)} |",
        f"| **Pages** | {len(unpublished_pages)} |",
        f"| **Total** | {total} |",
        "",
    ]

    for kind_name, entries in [("Posts", unpublished_posts), ("Pages", unpublished_pages)]:
        if entries:
            lines += ["", f"## Unpublished {kind_name}", "", "| ID | Status |", "|----|--------|"]
            def _norm(e):
                if isinstance(e, dict):
                    return e.get("id", 0), e.get("first_seen", "?")
                if isinstance(e, (list, tuple)) and len(e) > 0:
                    return e[0], e[1] if len(e) > 1 else "?"
                return 0, "?"
            for iid, status in sorted((_norm(e) for e in entries), key=lambda x: x[0]):
                lines.append(f"| {iid} | {status} |")
            lines.append("")

    lines.append("*Auto-generated by monitor*")
    lines.append("")

    out_path = MIRROR_DIR / "UNPUBLISHED_IDS.md"
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    log(f"Unpublished report: {out_path}", "FILE")


def _ensure_dirs():
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    DIFF_DIR.mkdir(parents=True, exist_ok=True)


def _fmt_size(bytes_val):
    for unit in ("B", "KB", "MB", "GB"):
        if bytes_val < 1024:
            return f"{bytes_val:.1f} {unit}"
        bytes_val /= 1024
    return f"{bytes_val:.1f} TB"


def _parse_changelog(path: Path) -> dict:
    if not path.is_file():
        return {}
    text = path.read_text(encoding="utf-8")
    entries = {}
    current = None
    history_lines = None
    in_details = False
    in_details_diff = False
    details_lines = None

    for line in text.splitlines():
        if line.startswith("### "):
            if current is not None:
                if history_lines is not None:
                    _finalize_history_entry(current, history_lines)
                entries[current["url"]] = current
            url = line[4:].strip()
            current = {"url": url, "rel": "", "size": "", "history": []}
            history_lines = None
            in_details = False
            in_details_diff = False
            details_lines = None
        elif current is not None:
            if current["rel"] == "" and re.match(r'^`[^`]+`\s*\(', line):
                m = re.match(r'^`([^`]+)`\s*\(([^)]+)\)', line)
                if m:
                    current["rel"] = m.group(1)
                    current["size"] = m.group(2)
            elif line.startswith("<details>"):
                in_details = True
                in_details_diff = False
                details_lines = []
            elif line.startswith("</details>"):
                if details_lines is not None and current is not None:
                    ts = _extract_details_ts(details_lines)
                    current["history"].append({"timestamp": ts, "lines": details_lines[:]})
                in_details = False
                in_details_diff = False
                details_lines = None
            elif in_details:
                if line.startswith("```diff"):
                    in_details_diff = True
                elif line.startswith("```") and in_details_diff:
                    in_details_diff = False
                elif in_details_diff:
                    if not line.startswith("<"):
                        details_lines.append(line)
            elif line.startswith("```diff"):
                history_lines = []
            elif line.startswith("```"):
                if history_lines is not None:
                    _finalize_history_entry(current, history_lines)
                    history_lines = None
            else:
                if history_lines is not None:
                    history_lines.append(line)

    if current is not None:
        if history_lines is not None:
            _finalize_history_entry(current, history_lines)
        entries[current["url"]] = current

    return entries


def _finalize_history_entry(current: dict, lines: list):
    entry = {"timestamp": "", "is_binary": False, "lines": lines[:]}
    for l in lines:
        m = re.match(r"^# Timestamp: (.+)", l)
        if m:
            entry["timestamp"] = m.group(1)
            break
    current.setdefault("history", []).append(entry)


def _extract_details_ts(lines: list) -> str:
    for l in lines:
        m = re.match(r"^# Timestamp: (.+)", l)
        if m:
            return m.group(1)
    return ""


_NOISE_LINE_RES = [
    re.compile(r'^.*generated in \d+\.\d+ seconds$'),
    re.compile(r'^.*\d+ bytes batcached for \d+ seconds$'),
    re.compile(r'^.*generated \d+ seconds? ago$'),
    re.compile(r'^.*served from batcache in \d+\.\d+ seconds$'),
    re.compile(r'^.*expires in \d+ seconds$'),
]


def _filter_noise_diff_lines(lines: list) -> list:
    return [l for l in lines if not any(r.match(l) for r in _NOISE_LINE_RES)]


def generate_id_series_report():
    import json
    api_base = MIRROR_DIR / "api" / "wp-json" / "wp" / "v2"

    all_posts = _collect_items(api_base / "posts")
    all_pages = _collect_items(api_base / "pages")
    all_media = _collect_items(api_base / "media")

    if not any([all_posts, all_pages, all_media]):
        return

    lines = [
        "# Post/Page/Media ID Series Analysis",
        "",
        f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
        f"**Source:** https://project-skyscraper.com/wp-json/wp/v2/{{posts,pages,media}}",
        "",
        "IDs are categorized by digit count:",
        "",
        "| Series | Digit Count | Range |",
        "|--------|-------------|-------|",
        "| **A** | 3-digit | < 1000 |",
        "| **B** | 4-digit | 1000-9999 |",
        "| **C** | Other | >= 10000 |",
        "",
    ]

    type_map = {}
    for iid, date, slug in all_posts:
        type_map[iid] = "post"
    for iid, date, slug in all_pages:
        type_map[iid] = "page"
    for iid, date, slug in all_media:
        type_map[iid] = "media"

    for label, limit in [("A: (3-digit)", 1000), ("B: (4-digit)", 10000)]:
        subset = sorted(
            [(iid, date, slug) for iid, date, slug in all_posts + all_pages + all_media
             if iid < limit and iid >= (0 if label.startswith("A") else 1000)],
            key=lambda x: x[0]
        )
        if subset:
            lines.append(f"### Series {label}")
            lines.append("")
            lines.append("```")
            lines.append(f"    {'ID':>6}   {'Delta':>6}   {'Date':<12}   {'Type':<8}   Slug")
            lines.append("    " + "-" * 60)
            for idx, (iid, date, slug) in enumerate(subset):
                if idx == 0:
                    delta = "  --"
                else:
                    d = iid - subset[idx - 1][0]
                    delta = f"{d:+5d}"
                typ = type_map.get(iid, "?")
                lines.append(f"    {iid:>6}   {delta:>6}   {date[:19]:<12}   {typ:<8}   {slug}")
            lines.append("```")
            lines.append("")

    lines.append("*Auto-generated by monitor*")
    lines.append("")

    time_table = _generate_time_reference_table(all_posts, all_pages)
    if time_table:
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.extend(time_table)

    out_path = MIRROR_DIR / "POST_ID_SERIES.md"
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    log(f"ID series report: {out_path}", "FILE")


def _collect_items(dir_path):
    items = []
    if dir_path.is_dir():
        for jf in sorted(dir_path.glob("*.json")):
            try:
                data = json.loads(jf.read_bytes())
            except Exception:
                continue
            if isinstance(data, dict) and "id" in data:
                items.append((data["id"], data.get("date", ""), data.get("slug", "")))
    return items


def _generate_time_reference_table(all_posts, all_pages):
    import re
    from pathlib import Path as _Path

    rows = []
    for pid, date, slug in all_posts + all_pages:
        link = ""
        for iid, d, s in all_posts:
            if iid == pid:
                link = f"https://project-skyscraper.com/{d[:4]}/{d[5:7]}/{d[8:10]}/{s}/"
                break
        for iid, d, s in all_pages:
            if iid == pid:
                link = f"https://project-skyscraper.com/{d[:4]}/{d[5:7]}/{d[8:10]}/{s}/"
                break

        url_date = _parse_url_date(link)
        content_type = "post" if pid in {i for i,_,_ in all_posts} else "page"

        api_base = MIRROR_DIR / "api" / "wp-json" / "wp" / "v2" / ("posts" if content_type == "post" else "pages")
        jf_path = api_base / f"{pid}.json"
        api_date = date
        api_date_gmt = ""
        api_modified = ""
        api_modified_gmt = ""
        if jf_path.is_file():
            try:
                jd = json.loads(jf_path.read_bytes())
                api_date = jd.get("date", date)
                api_date_gmt = jd.get("date_gmt", "")
                api_modified = jd.get("modified", "")
                api_modified_gmt = jd.get("modified_gmt", "")
            except Exception:
                pass

        visible_date = ""
        meta_published = ""
        meta_modified = ""
        epochs = ""

        html_dir = MIRROR_DIR / "html"
        for hf in html_dir.rglob(f"{slug}.html"):
            try:
                ht = hf.read_text(encoding="utf-8", errors="replace")
            except Exception:
                continue
            m = re.search(r'<time\s+datetime="([^"]+)"', ht)
            if m:
                visible_date = m.group(1)
            m = re.search(r'<meta\s+property="article:published_time"\s+content="([^"]+)"', ht)
            if m:
                meta_published = m.group(1)
            m = re.search(r'<meta\s+property="article:modified_time"\s+content="([^"]+)"', ht)
            if m:
                meta_modified = m.group(1)
            epoch_strs = []
            for m in re.finditer(r'memory\s+bloc\s+(\d{9,10})', ht, re.IGNORECASE):
                ts = int(m.group(1))
                if 1000000000 < ts < 2000000000:
                    from datetime import datetime as _dt
                    epoch_strs.append(f"memory_bloc={_dt.fromtimestamp(ts, tz=timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}")
            epochs = "; ".join(epoch_strs)
            break

        rows.append({
            "id": pid, "type": content_type, "slug": slug,
            "url_date": url_date or "", "api_date": api_date,
            "api_date_gmt": api_date_gmt, "api_modified": api_modified,
            "api_modified_gmt": api_modified_gmt, "visible_date": visible_date,
            "meta_published": meta_published, "meta_modified": meta_modified,
            "epochs": epochs,
        })

    if not rows:
        return []

    def sort_key(r):
        for field in ["api_date_gmt", "meta_published", "visible_date", "api_date", "url_date"]:
            v = r.get(field, "")
            if v:
                return v
        return ""
    rows.sort(key=sort_key)

    lines = [
        "# Post/Page Time Reference Analysis",
        "",
        f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
        "**Source:** https://project-skyscraper.com/wp-json/wp/v2/{posts,pages}",
        "",
        "Every available time reference for each published post/page, sorted by the time",
        "a viewer would have first seen it on the website (publish date).",
        "",
        "### Key",
        "",
        "| Column | Source | Description |",
        "|--------|--------|-------------|",
        "| **ID** | REST API | Post/page numeric ID |",
        "| **Type** | REST API | `post` or `page` |",
        "| **Slug** | REST API | URL slug |",
        "| **URL-date** | Permalink | Date extracted from the post URL |",
        "| **API date** | REST API `date` | Creation date (site timezone) |",
        "| **API date (GMT)** | REST API `date_gmt` | Creation date (UTC) |",
        "| **API modified** | REST API `modified` | Last modified (site timezone) |",
        "| **API modified (GMT)** | REST API `modified_gmt` | Last modified (UTC) |",
        "| **Visible date** | HTML `<time>` | Date shown to visitors on the page |",
        "| **Meta published** | HTML `<meta property>` | Open Graph published_time |",
        "| **Meta modified** | HTML `<meta property>` | Open Graph modified_time |",
        "| **Epoch timestamps** | Page content | Unix epoch timestamps |",
        "",
        "### Time Reference Table",
        "",
        "| ID | Type | Slug | URL-date | API date | API date (GMT) | API modified | API modified (GMT) | Visible date | Meta published | Meta modified | Epoch timestamps |",
        "|----|------|------|----------|----------|----------------|--------------|--------------------|--------------|----------------|---------------|------------------|",
    ]

    for r in rows:
        lines.append(
            f"| {r['id']} | {r['type']} | {r['slug']} "
            f"| {r['url_date']} | {r['api_date']} | {r['api_date_gmt']} "
            f"| {r['api_modified']} | {r['api_modified_gmt']} "
            f"| {r['visible_date']} | {r['meta_published']} | {r['meta_modified']} "
            f"| {r['epochs']} |"
        )

    lines.append("")
    lines.append("*Auto-generated by monitor*")
    lines.append("")
    return lines


def _parse_url_date(link):
    import re
    m = re.search(r'/(\d{4})/(\d{2})/(\d{2})/', link)
    if m:
        return f"{m.group(1)}-{m.group(2)}-{m.group(3)}"
    return ""


def refresh_reports(state: dict):
    """Regenerate all markdown reports from current state and mirror data.
    Called by the daemon after each deep cycle."""
    log("=== REFRESHING MARKDOWN REPORTS ===")

    # Walk mirror for manifest stats
    total_files = 0
    total_size = 0
    section_data = {}
    for root, dirs, files in os.walk(str(MIRROR_DIR)):
        dirs[:] = [d for d in dirs if d not in (".git", "__pycache__", "state", "monitor_reports")]
        for fn in files:
            fp = os.path.join(root, fn)
            rel = os.path.relpath(fp, str(MIRROR_DIR))
            sz = os.path.getsize(fp)
            total_files += 1
            total_size += sz
            section = rel.replace("\\", "/").split("/")[0]
            section_data.setdefault(section, {"files": 0, "size": 0})
            section_data[section]["files"] += 1
            section_data[section]["size"] += sz

    generate_manifest_report(section_data, total_files, total_size)
    generate_id_series_report()

    unpublished_posts = state.get("probe", {}).get("unpublished", {}).get("posts", [])
    unpublished_pages = state.get("probe", {}).get("unpublished", {}).get("pages", [])
    generate_unpublished_report(unpublished_posts, unpublished_pages)

    # Regenerate CHANGELOG.md from existing diff files
    meaningful = []
    diff_dir = DIFF_DIR
    if diff_dir.is_dir():
        for df in sorted(diff_dir.iterdir()):
            if df.suffix == ".diff":
                content = df.read_text(encoding="utf-8", errors="replace")
                rel_path = df.name.replace(".diff", "")
                if content.strip():
                    meaningful.append(("", df, content, rel_path))
    if meaningful:
        write_changelog(meaningful)

    log("Markdown reports refreshed", "FILE")
