"""Report writer -- local markdown & JSON report generation."""

import json
import os
import re
import time
from datetime import datetime, timezone
from pathlib import Path
from collections import defaultdict

from monitor.config import MIRROR_DIR, REPORT_DIR, DIFF_DIR
from monitor.logger import log


def write_monitor_report(category: str, data: dict):
    _ensure_dirs()
    ts = datetime.now(timezone.utc)
    filename = f"{ts.strftime('%Y%m%d_%H%M%S')}_{category}.json"
    path = REPORT_DIR / filename
    report = {
        "timestamp": ts.strftime("%Y-%m-%d %H:%M:%S UTC"),
        "category": category,
        "data": data,
    }
    path.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    log(f"Report written: {path.name}", "FILE")

    latest = REPORT_DIR / f"latest_{category}.json"
    latest.write_text(path.name, encoding="utf-8")


def write_changelog(changes: list):
    from monitor.noise_filter import diff_has_real_changes

    changelog_path = DIFF_DIR / "CHANGELOG.md"
    DIFF_DIR.mkdir(parents=True, exist_ok=True)

    existing = _parse_changelog(changelog_path)
    new_entries = {}

    for url, path, diff_content, rel in changes:
        sz = _fmt_size(path.stat().st_size)
        is_real = diff_content and diff_has_real_changes(diff_content)

        if not is_real and diff_content is None:
            continue

        old_entry = existing.get(url, {})
        history = []
        if old_entry:
            for h in old_entry.get("history", []):
                history.append(h)

        current_lines = diff_content.splitlines() if diff_content else None
        new_entries[url] = {
            "rel": rel,
            "size": sz,
            "current_diff": current_lines,
            "history": history,
        }

    if not new_entries:
        return

    lines = [
        "# Change Report",
        "",
        f"Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
        "",
        f"**{len(new_entries)} file(s) with meaningful changes**",
        "",
    ]

    for url in sorted(new_entries.keys()):
        entry = new_entries[url]
        lines += [f"### {url}", f"`{entry['rel']}` ({entry['size']})", ""]

        if entry["current_diff"] is not None:
            lines.append("```diff")
            lines += _filter_noise_diff_lines(entry["current_diff"])
            if lines[-1] == "```":
                lines[-1] = ""
            lines.append("```")
            lines.append("")
        else:
            lines.append("*No line-level diff available*")
            lines.append("")

        for h in entry["history"]:
            ts = h.get("timestamp", "")
            label = f"Previous diff ({ts})" if ts else "Previous diff"
            hist_lines = _filter_noise_diff_lines(h.get("lines", []))
            lines.append("<details>")
            lines.append(f"<summary>{label}</summary>")
            lines.append("")
            lines.append("```diff")
            if hist_lines and hist_lines[-1] == "```":
                lines += hist_lines[:-1]
            else:
                lines += hist_lines
            lines.append("```")
            lines.append("")
            lines.append("</details>")
            lines.append("")

    lines.append("*Auto-generated by monitor*")
    lines.append("")

    changelog_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    log(f"Changelog written: {changelog_path} ({len(new_entries)} files)", "FILE")


def clean_old_reports(max_age_hours: int = 72):
    cutoff = time.time() - (max_age_hours * 3600)
    for f in REPORT_DIR.glob("*.json"):
        if f.name.startswith("latest_"):
            continue
        try:
            if f.stat().st_mtime < cutoff:
                f.unlink()
        except OSError:
            pass


def generate_manifest_report(stats_by_dir: dict, total_files: int, total_size: int):
    lines = [
        "# project-skyscraper.com -- Complete Mirror Manifest",
        "",
        f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
        f"**Source:** https://project-skyscraper.com",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| **Total files** | {total_files} |",
        f"| **Total size** | {_fmt_size(total_size)} |",
        "",
        "## Section Breakdown",
        "",
        "| Section | Files | Size |",
        "|---------|-------|------|",
    ]
    for section in sorted(stats_by_dir):
        if section in (".git", "__pycache__", "state", "monitor_reports"):
            continue
        d = stats_by_dir[section]
        lines.append(f"| **{section}/** | {d['files']} | {_fmt_size(d['size'])} |")
    lines += ["", "*Auto-generated by monitor*", ""]
    manifest_path = MIRROR_DIR / "MIRROR_MANIFEST.md"
    manifest_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    log(f"Manifest written: {manifest_path}", "FILE")


def generate_unpublished_report(unpublished_posts: list, unpublished_pages: list):
    if not unpublished_posts and not unpublished_pages:
        return

    total = len(unpublished_posts) + len(unpublished_pages)
    lines = [
        "# Unpublished / Restricted IDs Report",
        "",
        f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
        f"**Source:** https://project-skyscraper.com/wp-json/wp/v2/{{posts,pages}}/{{id}}",
        "",
        "IDs returning 401 or 403 indicate content that exists but is not publicly",
        "accessible (drafts, private, etc.).",
        "",
        "## Summary",
        "",
        "| Type | Count |",
        "|------|-------|",
        f"| **Posts** | {len(unpublished_posts)} |",
        f"| **Pages** | {len(unpublished_pages)} |",
        f"| **Total** | {total} |",
        "",
    ]

    for kind_name, entries in [("Posts", unpublished_posts), ("Pages", unpublished_pages)]:
        if entries:
            lines += ["", f"## Unpublished {kind_name}", "", "| ID | Status |", "|----|--------|"]
            for iid, status in sorted(entries):
                lines.append(f"| {iid} | {status} |")
            lines.append("")

    lines.append("*Auto-generated by monitor*")
    lines.append("")

    out_path = MIRROR_DIR / "UNPUBLISHED_IDS.md"
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    log(f"Unpublished report: {out_path}", "FILE")


def _ensure_dirs():
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    DIFF_DIR.mkdir(parents=True, exist_ok=True)


def _fmt_size(bytes_val):
    for unit in ("B", "KB", "MB", "GB"):
        if bytes_val < 1024:
            return f"{bytes_val:.1f} {unit}"
        bytes_val /= 1024
    return f"{bytes_val:.1f} TB"


def _parse_changelog(path: Path) -> dict:
    if not path.is_file():
        return {}
    text = path.read_text(encoding="utf-8")
    entries = {}
    current = None
    history_lines = None
    in_details = False
    in_details_diff = False
    details_lines = None

    for line in text.splitlines():
        if line.startswith("### "):
            if current is not None:
                if history_lines is not None:
                    _finalize_history_entry(current, history_lines)
                entries[current["url"]] = current
            url = line[4:].strip()
            current = {"url": url, "rel": "", "size": "", "history": []}
            history_lines = None
            in_details = False
            in_details_diff = False
            details_lines = None
        elif current is not None:
            if current["rel"] == "" and re.match(r'^`[^`]+`\s*\(', line):
                m = re.match(r'^`([^`]+)`\s*\(([^)]+)\)', line)
                if m:
                    current["rel"] = m.group(1)
                    current["size"] = m.group(2)
            elif line.startswith("<details>"):
                in_details = True
                in_details_diff = False
                details_lines = []
            elif line.startswith("</details>"):
                if details_lines is not None and current is not None:
                    ts = _extract_details_ts(details_lines)
                    current["history"].append({"timestamp": ts, "lines": details_lines[:]})
                in_details = False
                in_details_diff = False
                details_lines = None
            elif in_details:
                if line.startswith("```diff"):
                    in_details_diff = True
                elif line.startswith("```") and in_details_diff:
                    in_details_diff = False
                elif in_details_diff:
                    if not line.startswith("<"):
                        details_lines.append(line)
            elif line.startswith("```diff"):
                history_lines = []
            elif line.startswith("```"):
                if history_lines is not None:
                    _finalize_history_entry(current, history_lines)
                    history_lines = None
            else:
                if history_lines is not None:
                    history_lines.append(line)

    if current is not None:
        if history_lines is not None:
            _finalize_history_entry(current, history_lines)
        entries[current["url"]] = current

    return entries


def _finalize_history_entry(current: dict, lines: list):
    entry = {"timestamp": "", "is_binary": False, "lines": lines[:]}
    for l in lines:
        m = re.match(r"^# Timestamp: (.+)", l)
        if m:
            entry["timestamp"] = m.group(1)
            break
    current.setdefault("history", []).append(entry)


def _extract_details_ts(lines: list) -> str:
    for l in lines:
        m = re.match(r"^# Timestamp: (.+)", l)
        if m:
            return m.group(1)
    return ""


_NOISE_LINE_RES = [
    re.compile(r'^.*generated in \d+\.\d+ seconds$'),
    re.compile(r'^.*\d+ bytes batcached for \d+ seconds$'),
    re.compile(r'^.*generated \d+ seconds? ago$'),
    re.compile(r'^.*served from batcache in \d+\.\d+ seconds$'),
    re.compile(r'^.*expires in \d+ seconds$'),
]


def _filter_noise_diff_lines(lines: list) -> list:
    return [l for l in lines if not any(r.match(l) for r in _NOISE_LINE_RES)]
